### ISSUE TITLE
Unable to Build Site following the Github_Token Instructions (Step 3)

### ISSUE THREAD

**Issue by DrCatman** [thakkaryash94/thakkaryash94.github.io#2]
When I follow the step 3 of "Install in your local development environment"

>    3. Build the site and make it available on a local server

`GITHUB_TOKEN=YOUR_GITHUB_TOKEN npm run develop`

I get the following error:

```
'GITHUB_TOKEN' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by thakkaryash94** [comment]
I forgot to mention this only works in Linux and mac. I assume from the error, you are using windows. So you can use Git Bash or you have to follow here https://stackoverflow.com/questions/1420719/powershell-setting-an-environment-variable-for-a-single-command-only

**Comment by DrCatman** [comment]
Got it. Thank you!
